app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('', views.home, name='home'),
    
    path('marketplace/', views.placements, name='placements'),
    path('marketplace/<placement_slug>/', views.placement_detail, name='placement-detail'),

    path('my-bids/', views.bid_summary, name='bid-summary' ),
    path('confirm-bids/', views.confirm_bids, name='confirm-bids'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about')
]

bid_it/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))
]

app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.

class Company(models.Model):
    """
    Simply contains company details, referenced by Placement model
    """

    company_name = models.CharField(max_length=255)
    company_address = models.CharField(max_length=255)
    company_description = models.TextField(default="There is currently no description available for this company.")

    company_created = models.DateTimeField(auto_now_add=True)
    company_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.company_name


class Placement(models.Model):
    """
    A placement allows investors to bid on company capital raise
    """

    placement_title = models.CharField(max_length=255)
    placement_slug = models.SlugField()
    placement_company = models.ForeignKey(Company, on_delete=models.CASCADE)


    placement_created = models.DateTimeField(auto_now_add=True)
    placement_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.placement_title


class Bid(models.Model):
    """
    The bid, synonmous with 'order'
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=True)
    bid_status = models.BooleanField(default=False)

    bid_created = models.DateTimeField(auto_now_add=True)
    bid_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} -{}'.format(self.user, self.bid_status)


class PlacementBid(models.Model):
    """
    The junction table for placement and bid models/tables. Contains every instance of a bid for a placement
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE,default=True)
    placement = models.ForeignKey(Placement, on_delete=models.CASCADE)
    bid  = models.ForeignKey(Bid, on_delete=models.CASCADE)
    offer = models.IntegerField()
    shares = models.IntegerField()
    confirmed = models.BooleanField(default=False)
    
    placementbid_created = models.DateTimeField(auto_now_add=True)
    placementbid_modified = models.DateTimeField(auto_now=True)

    class Meta: 
        ordering = ['-placementbid_modified'] 

    def __str__(self):
        return '{} - {} - {}'.format(self.shares, self.offer, self.user)

app/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CustomRegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomRegisterForm
from .models import Placement, PlacementBid, Bid, Company
from django.contrib.auth.models import User
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum, Avg, Count


def register(request):
    if request.method == 'POST':
        form = CustomRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:login')
    else:
        form = CustomRegisterForm()
    
    context = {'form': form}

    return render(request, 'register.html', context)


def login(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('app:home')
        else:
            return render(request, 'login.html') 
            
    else:
        return render(request, 'login.html') 


def home(request):

    return render(request, 'home.html')


@login_required
def logout(request):
    auth_logout(request)
    return redirect('app:login')


@login_required
def placements(request):
    
    all_placements = Placement.objects.all()

    paginator = Paginator(all_placements, 18)
    page = request.GET.get('page')
    placements = paginator.get_page(page)

    context = {'placements': placements}

    return render(request, 'placements.html', context)


@login_required
def placement_detail(request, placement_slug):

    placement = get_object_or_404(Placement, placement_slug=placement_slug)

    if request.method == 'POST':
        submitted_quantity = request.POST.get('quantity')
        submitted_amount = request.POST.get('amount')

        # Create or store Bid object based on conditional
        bid_queryset = Bid.objects.filter(user=request.user, bid_status=False)
        
        if bid_queryset.exists():
            bid = bid_queryset[0]
        else:
            bid = Bid.objects.create(user=request.user)
        
        # Create PlacementBid given the above objects
        placement_bid = PlacementBid.objects.create(user=request.user, 
                                                    placement=placement, 
                                                    bid=bid,
                                                    offer=submitted_amount,
                                                    shares=submitted_quantity)
        return redirect("/my-bids/")

    context = {'placement': placement}

    return render(request, 'placement_detail.html', context)


@login_required
def bid_summary(request):

    bids = PlacementBid.objects.filter(user=request.user)

    context = {'bids': bids}

    return render(request, 'bid-summary.html', context)



@login_required
def confirm_bids(request):

    bids_queryset = PlacementBid.objects.filter(user=request.user, confirmed=False)
    
    if bids_queryset.exists():

        # First get the order ID
        bid_id = bids_queryset[0].bid.id

        # Update PlacementBid Objects confirmed flag
        for bid in bids_queryset:
            bid.confirmed = True
            bid.save()
        
        # Update the Bid object status
        bid = Bid.objects.filter(id=bid_id)[0]
        bid.bid_status = True
        bid.save()

    return redirect('app:bid-summary')


def about(request):

    return render(request, 'about.html')


@login_required
def dashboard(request):
    
    # Get tile data
    total_companies = Company.objects.count()
    total_users = User.objects.count()
    total_placements = Placement.objects.count()
    total_offers = PlacementBid.objects.aggregate(Sum('offer'))['offer__sum']
    total_offers_k = total_offers // 1000
    
    # Get aggregate data
    top_5 = PlacementBid.objects\
                    .values('placement__placement_company__company_name', 'offer')\
                    .annotate(Sum('offer'))\
                    .order_by('-offer')[:5]

    top_5_offer_names = [item['placement__placement_company__company_name'] for item in top_5]
    top_5_offer_names = [name[:8] + '...' for name in top_5_offer_names]
    top_5_offer_values = [item['offer'] for item in top_5]

    # Store context
    context = {'total_companies':total_companies,
                'total_users':total_users,
                'total_placements':total_placements,
                'total_offers':total_offers_k,
                'top_5_offer_names':top_5_offer_names,
                'top_5_offer_values':top_5_offer_values}

    return render(request, 'dashboard.html', context)

templates/bid-summary.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}
{% load static %}
<section class="section">
    <section class="container">
        <div class="card" style="border: 3px solid gold; border-radius: 10px;">
            <div class="card-content">
                <h3>Your bid summary</h3>
                <br>
                <h6>Please Scroll Down⬇</h6>
                <div class="card-content">
                    <div class="col s12 m7">
                        <div  class="card" style="box-shadow: 10px 10px 5px lightblue;">
                            <div class="card-image">
                                
                                <img  src="{% static 'biddy3.webp' %}">
                                <span class="card-title" style="font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif; color: black;">&nbsp; &nbsp;&nbsp;Bid Summary</span>
                            </div>
                            <div class="card-content">
                                <p><strong>Check and Confirm your bids!</strong></p>
                            </div>
                            <!-- <div class="card-action">
                                <a href=" https://economictimes.indiatimes.com/topic/bidding-system">News🌐</a>
                            </div> -->
                        </div>
                <table class="striped centered responsive-table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Bid status</th>
                            <th>Company Name</th>
                            <th>Timestamp</th>
                            <th>$ Bidded</th>
                            <th>no. Shares</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for b in bids %}
                        <tr>
                            <td>{{ b.id }}</td>
                            <td>{% if b.confirmed %}<span class="chip"
                                    style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Confirmed</span>{%else%}
                                <span class="chip red darken-2 white-text"
                                    style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Unconfirmed</span>
                                {%endif%}</td>
                            <td>{{ b.placement.placement_company }}</td>
                            <td>{{ b.placementbid_created }}</td>
                            <td>{{ b.offer}}</td>
                            <td>{{ b.shares}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <a  href="{% url 'app:confirm-bids' %}" data-target="modal1" data-position="right" data-tooltip="Click to confirm all your bids" onclick="  M.toast({html: 'Confirm?', inDuration:5000, outDuration:6000, displayLength:1000, classes:'rounded', activationPercent:10000});" style="margin-top: 1rem;"
                    class="btn tooltipped btn waves-orange waves-effect pink btn modal-trigger">Confirm<i
                        class="material-icons right">check_circle</i>
                </a>
                <div id="modal1" class="modal">
                    <div class="modal-content">
                      <h4>Confirm?</h4>
                      <p><strong>Do you want to confirm all your bids?</strong></p>
                    </div>
                    <div class="modal-footer">
                        <a href="{% url 'app:bid-summary' %}" onclick="M.toast({html: 'Not confirmed', inDuration:5000, outDuration:6000, displayLength:1000, classes:'rounded', activationPercent:10000});" class="btn waves-orange waves-effect pink">Cancel</a>
                        &nbsp;
                        <a href="{% url 'app:confirm-bids' %}"  onclick="M.toast({html: 'Confirmed', inDuration:5000, outDuration:6000, displayLength:1000, classes:'rounded', activationPercent:10000});" class=" btn waves-orange waves-effect pink">OK</a>
                    </div>
                  </div>
            </div>
        </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  
<footer class="page-footer red darken-1">
  
  <div class="container">
    <div class="col l4 offset-l4 s12">
      <a class="black-text text-lighten-2" href="#!"> <strong>FAQ</strong>  &nbsp;&nbsp;&nbsp;</a>
      <a class="black-text text-lighten-2" href="#!"> <strong>Contac Us</strong>  &nbsp;&nbsp;&nbsp;</a>
      <a class="black-text text-lighten-2" href="{% url 'app:about' %}"> <strong>Terms of Use</strong>  &nbsp;&nbsp;&nbsp;</a>
      <a class="black-text text-lighten-2" href="{% url 'app:about' %}"> <strong>Privacy Policy</strong>  &nbsp;&nbsp;&nbsp;</a>
      <a class="black-text text-lighten-2" href="{% url 'app:about' %}"> <strong> Refund Policy</strong> &nbsp;&nbsp;&nbsp;</a>
      <br>
      <br>
    </div>
  </div>
  </div>
  <div class="footer-copyright pink lighten-1">
    <div class="container center custom-font-1">
      © 2022 Copyright Text

    </div>
  </div>
</footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %} {% load static %}

<section class="section">
    <section class="container">
        <article class="card" style="border-radius: 10px; background-color: black;">
            <div class="card-content">
                <h4 style="color: white; font-family: 'Pacifico', cursive;">Welcome!</h4>
            </div>

        </article>
    </section>

</section>

<section class="section" style="padding-top: 70px;"> 
    <section class="container">
        <div class="card z-depth-2" style="margin-top:-10%">
            <div class="card-content" style="background-color: black;">
                <div class=" carousel" style="background-color: black; margin-bottom: -50x;">
                    <a class="carousel-item" href="{% url 'app:about' %}" style="height: 450px; width: 450px;"><img
                            src="{% static 'slide.png' %}"></a>
                    <a class="carousel-item" href="{% url 'app:placements' %}" style="height: 450px; width: 450px;"><img
                            src="{% static 'biddy2.jpg' %}"></a>
                    <a class="carousel-item" href="{% url 'app:bid-summary' %}" style="height: 450px; width: 450px;"><img
                            src="{% static 'graph1.gif' %}"></a>
                </div>
            </div>
        </div>
    </section>
</section>

<section class="section">

    <section class="container">

        {% if user.is_authenticated == False %}
        <div class="card z-depth-2" style="margin-top:-05%">
            <div class="card-content" style="border: 3px solid gold; border-radius: 10px;">
                <h5>Notice</h5>
                <p class="custom-font-1">You must have a registered account and be logged in, in order to view and place
                    bids within our marketplace.</p>
            </div>
        </div>
        {% endif %}

        <div class="card z-depth-2" style="border: 3px solid gold; border-radius: 10px; ">
            <div class="card-content">
                <h5>The Current Market</h5>
                <blockquote>
                    <p class="custom-font-1">The existence of a ‘bidding market’ is commonly cited as a reason to
                        tolerate
                        the creation or maintenance of highly concentrated markets. We discuss three erroneous arguments
                        to
                        that effect: the ‘consultants’ fallacy’ that ‘market power is impossible’, the ‘academics’
                        fallacy’
                        that (often) ‘market power does not matter’, and the ‘regulators’ fallacy’ that ‘intervention
                        against pernicious market power is unnecessary’, in markets characterized by auctions or bidding
                        processes</p>
                </blockquote>
                <!--                <a href="{% url 'app:placements' %}" class="btn waves-effect waves-light pink" style="margin-top: 1rem;">-->
                <!--                        <i class="material-icons left">store</i>visit marketplace</a>-->
                <img class="responsive-img fade-in card-panel hoverable" src="{% static 'bidgif2.gif' %}" alt="">
            </div>
        </div>


        <div class="card z-depth-2" style="border: 3px solid gold; border-radius: 10px;">
            <div class="card-content">
                <h5>
                    Bidding News
                </h5>
                <blockquote>
                    <p class="custom-font-1">India head Sanjay Malik said that if the auction takes place around
                        May-June
                        period, then the initial 5G network rollouts can start in the second half of the year. The
                        company
                        had rolled out over 1,50,000 sites in India for its telecom operator partners for both capacity
                        and
                        coverage requirements in 2021..</p>
                    <p class="custom-font-1"><br>Norms are being worked out for new frequencies such as 526-698 MHz and
                        millimetre band, that is 24.25 - 28.5 GHz, in addition to bands such as 700 MHz, 800 MHz, 900
                        MHz,
                        1800 MHz, 2100 MHz, 2300 MHz, 2500 MHz, 3300-3670 MHz</p>
                    <p class="custom-font-1"><br>Telecom Minister Ashwini Vaishnaw earlier this month said the Trai has
                        informed that it will submit its recommendations for the 5G auction by March and the Department
                        of
                        Telecommunications (DoT) is simultaneously firming up other processes to hold the auction at the
                        earliest.</p>
                </blockquote>
                <!-- <img class="responsive-img fade-in" src="{% static 'office.png' %}" alt=""> -->
                <div class="col s12 m7">
                    <div class="card" style="box-shadow: 10px 10px 5px lightblue;">
                        <div class="card-image">
                            <img src="{% static 'office.png' %}">
                            <span class="card-title"
                                style="font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">&nbsp;
                                &nbsp;&nbsp;Latest News</span>
                        </div>
                        <div class="card-content">
                            <p><strong> To get updated with latest news please visit the link below</strong></p>
                        </div>
                        <div class="card-action">
                            <a target="_blank" href=" https://economictimes.indiatimes.com/topic/bidding-system">Link:
                                News🌐</a>
                        </div>
                    </div>
                </div>


            </div>
        </div>


        <div class="card z-depth-2" style="border: 3px solid gold; border-radius: 10px;">
            <div class="card-content">
                <h5>
                    About
                </h5>
                <p class="custom-font-1">The bidding process is used to select a vendor for subcontracting a project, or
                    for purchasing products and services that are required for a project. Bid records contain the
                    specifications of the project or details of the products and services to be purchased.</p>
                <blockquote>
                    <ol class="custom-font-1">
                        <li>
                            <p class="black-text text-lighten-2">The project manager or contract/purchasing manager
                                creates
                                a bid that describes the specifications and estimated cost of the project.</p>
                        </li>
                        <li>
                            <p class="black-text text-lighten-2">The manager issues the bid.</p>
                        </li>
                        <li>
                            <p class="black-text text-lighten-2">The manager sends the bid to a group of vendors for
                                response.</p>
                        </li>
                        <li>
                            <p class="black-text text-lighten-2">Terms & Conditions</p>
                        </li>
                        <li>
                            <p class="black-text text-lighten-2">The vendors analyze the bid and calculate the cost at
                                which
                                they can complete the project. Each vendor responds to the bid with details about the
                                products and services that are needed and the overall cost.</p>
                        </li>
                        <li>
                            <p class="black-text text-lighten-2">The manager manages and analyzes the bid responses.</p>
                        </li>
                        <li>
                            <p class="black-text text-lighten-2">Terms & ConditionsThe manager awards the bid to the
                                vendor
                                that best meets the requirements of the project.</p>
                        </li>
                        <li>
                            <p class="black-text text-lighten-2">A standard contract is automatically created by using
                                the
                                bid details and response information.</p>
                        </li>
                    </ol>
                </blockquote>
                <!-- <img class="responsive-img fade-in" src="{% static 'bidgif3.gif' %}" alt=""> -->
                <div class="col s12 m7">
                    <div class="card" style="box-shadow: 10px 10px 5px lightblue;">
                        <div class="card-image">
                            <img src="{% static 'bidgif3.gif' %}">
                            <span class="card-title"
                                style="font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;color: black;">&nbsp;
                                &nbsp;&nbsp;Process</span>
                        </div>
                        <div class="card-content">
                            <p><strong> To know more about the Bidding process please visit the link below</strong></p>
                        </div>
                        <div class="card-action">
                            <a target="_blank"
                                href="https://www.ibm.com/docs/SSFCZ3_10.5.3/com.ibm.tri.doc/proc_topics/c_bidding_process.html">Link:
                                Process🔁</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>




    </section>
</section>

{% include 'footer.html' %} {% endblock content %}
<!-- style="box-shadow: 10px 10px 5px lightblue;" -->
<!-- class="card-panel hoverable" -->

templates/login.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div class="row">
    <!-- <div class="col s12 m7"> -->
        <div class="card">
            <div class="card-image">
                <img height="330px" width="330px" src="{% static 'log.png' %}">
                <h4><span class="card-title" style="padding-bottom: 100px; font-family: 'Pacifico', cursive; font-size: 225%; ">&nbsp; Login page</span></h4>
            </div>
            <div class="card-content">
                <form action="" method="POST" class="form">
                    {% csrf_token %}
                    <div class="input-field" style="margin-top: -20px;">
                        <label for="" class="label">
                            <strong> Username</strong>
                        </label>
                        <input type="text" name="username">
                    </div>
                    <div class="input-field">
                        <label for="" class="label">
                            <strong>Password</strong> 
                        </label>
                        <input type="password" name="password">
                    </div>
                    <div class="input-field">
                        <button style="margin-top: 1rem;" class="btn waves-effect waves-orange black lighten-4"
                            type="submit">Login</button>
                    </div>
                    <strong>
                    <p>Don't have an account? click <a href="{% url 'app:register' %}" style="margin-top: 1rem; color: red"
                            type="a">here</a> to register.</p>
                    <p>Don't have time to sign up? Use the guest account credentials below.</p></strong>
                    <p class="chip">username: 'mahesh' password: '1234'</p>
                </form>
            </div>
            <!-- <div class="card-action">
                <a href="#">This is a link</a>
            </div> -->
        </div>
    <!-- </div> -->
</div>







<!-- 
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l8 m12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Login page</h5>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Username
                                    </label>
                                    <input type="text" name="username">
                                </div>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Password
                                    </label>
                                    <input type="password" name="password">
                                </div>
                                <div class="input-field">
                                    <button style="margin-top: 1rem;" class="btn waves-effect waves-light pink"
                                        type="submit">Login</button>
                                </div>
                                <p>Don't have an account? click <a href="{% url 'app:register' %}"
                                        style="margin-top: 1rem;" type="a">here</a> to register.</p>
                                <p>Don't have time to sign up? Use the guest account credentials below.</p>
                                <p class="chip">username: 'dc' password: '1'</p>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </section>

    </section>
</main> -->
{% include 'footer.html' %} {% endblock content %}

templates/nav.html
<nav  >
    <div class="nav-wrapper red darken-1 " style="padding-bottom: 70px; padding-top:2px;">
        <div class="center-align" style="padding-right: 150px;">
            <a style="color:white; font-family: 'Pacifico', cursive; font-size: 250%; background-color: black; border-radius: 30px; border: 2px indigo solid;;" href="" class="brand-logo">&nbsp;&nbsp; Bid It! &nbsp;&nbsp;</a>
        </div>
        <div class="container">    
            <a href="#" data-target="mobile-demo" class="sidenav-trigger waves-effect waves-light"><i
                    class="material-icons">menu</i></a>
            <ul class="left hide-on-med-and-down">
                <li><a href="{% url 'app:home' %}"><i class="material-icons" style="color:black;font-size: 34px;">home</i></a></li>
                <li><a href="{% url 'app:bid-summary' %}"><i class="material-icons"
                            style="color:black;font-size: 34px;">assignment</i></a></li>
                <li><a href="{% url 'app:placements' %}"><i class="material-icons" style="color:black;font-size: 34px;">local_atm</i></a>
                </li>
                <li><a href="{% url 'app:about' %}"><i class="material-icons" style="color:black;font-size: 34px;">help</i></a></li>

            </ul>

            <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li> Profile:<strong>{{ user.username }}</strong> &nbsp;&nbsp;&nbsp;&nbsp;</li>
                
                
                <li><a class="btn-small  waves-orange waves-effect grey darken-4" href="{% url 'app:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a class="btn-small waves-effect waves-orange black" href="{% url 'app:register' %}">
                        Register
                    </a>
                </li>
                <li>
                    <a class="btn-small waves-effect waves-orange black" href="{% url 'app:login' %}">
                        Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<ul class="sidenav" id="mobile-demo" style="background-color: black;">
    <br>

    <a style="color:white; font-family: 'Pacifico', cursive; font-size: 250%; background-color: black; border-radius: 30px; border: 2px gold solid;margin-left:50px" href="" class="brand-logo">&nbsp;&nbsp;Bid It!&nbsp;&nbsp;</a>
    <br>
    <br>
    <li><a href="{% url 'app:home' %}" style="color: white; font-size: 30;"><i class="material-icons"
                style="color:white">home</i><strong> Home</strong></a></li>
    <li><a href="{% url 'app:bid-summary' %}" style="color: white; font-size: 30;"><i class="material-icons"
                style="color:white">assignment</i><strong>Your Bids</strong> </a></li>
    <li><a href="{% url 'app:placements' %}" style="color: white; font-size: 30;"><i class="material-icons"
                style="color:white">local_atm</i><strong>Current Market</strong></a></li>
    <li><a href="{% url 'app:about' %}" style="color: white; font-size: 30;"><i class="material-icons"
                style="color:white">help</i><strong>About</strong> </a></li>
    <!--    <li><a href="{% url 'app:dashboard' %}"><i class="material-icons">insert_chart</i>Analytics</a></li>-->
    {% if user.is_authenticated %}
    <li><a class="btn-small waves-effect waves-orange grey darken-4" href="{% url 'app:logout' %}">Logout</a></li>
    {% else %}
    <li><a class="btn-small waves-effect waves-orange red" href="{% url 'app:register' %}">
            Register</a>
    </li>
    <li><a class="btn-small waves-effect waves-orange red" href="{% url 'app:login' %}">
            Login</a>
    </li>
    {% endif %}
</ul>